import PromptSync from 'prompt-sync';
import chalk from 'chalk';
const prompt = PromptSync();

export enum PrintCommand {
    AICall,
    UnitTest,
    Issue,
}

export class CommandLine {
    /// Get the user request.
    //
    public static getUserResponse(question: string): string {
        let answer = prompt(chalk.blue(question));
        if (!answer) {
            answer = 'Invalid answer';
        }
        return answer;
    }

    public static printAgentMessage(
        command: PrintCommand,
        agentPosition: string,
        agentStatement: string,
    ): void {
        // Get the color for the 'command'
        const printInColor = CommandLine.getStatementColor(command);

        // Print the agent position in green and the agent statement in the command color
        console.log(
            chalk.green(`Agent: ${agentPosition}: `) +
                printInColor(agentStatement),
        );
    }

    // TODO refactor this, it's ugly
    public static confirmSafeCode(): boolean {
        let validSelection = false;
        let answer = false;
        do {
            console.log('');
            console.log(
                'WARNING: You are about to run code generated by an AI. Review your code and confirm you wish to continue.',
            );
            console.log(chalk.green('[1] All good'));
            console.log(chalk.red("[2] Let's stop this project"));

            const response = this.getUserResponse('Enter selection: ');
            if (['1', 'ok', 'y'].includes(response)) {
                validSelection = true;
                answer = true;
            } else if (['2', 'no', 'n'].includes(response)) {
                validSelection = true;
                answer = false;
            }
        } while (!validSelection);

        return answer;
    }

    private static getStatementColor(
        command: PrintCommand,
    ): (output: string) => string {
        if (command === PrintCommand.Issue) {
            return chalk.red;
        } else if (command === PrintCommand.UnitTest) {
            return chalk.magenta;
        } else {
            return chalk.cyan;
        }
    }
}
